export const ADD_ONE_FILM = 'ADD_ONE_FILM';
export const REMOVE_ONE_FILM = 'REMOVE_ONE_FILM';
export const SET_NEW_CHARACTERS_LIST = 'SET_NEW_CHARACTERS_LIST';
export const SET_NEW_EPISODES_LIST = 'SET_NEW_EPISODES_LIST';
export const SET_NEW_LOCATIONS_LIST = 'SET_NEW_LOCATIONS_LIST';